server:
  port: 10155

spring:
  datasource:
    driver-class-name: org.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: demo
    password: demo


    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true