POST http://localhost:8080/notify/test
Content-Type: application/json

{
  "blocks": [
    {
      "type": "image",
      "title": {
        "type": "plain_text",
        "text": "Please enjoy this photo of a kitten"
      },
      "block_id": "image4",
      "image_url": "http://placekitten.com/500/500",
      "alt_text": "An incredibly cute kitten."
    }
  ]
}