spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/sample
    username: root
    password: root

notify:
  slack:
    url: https://hooks.slack.com/services
    token-path: TTS9Q7GAC/B0519CMM2LV/SliX5SSbn6cM6HGN5latlQGb
